In [10]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, r2_score, mean_squared_error, mean_absolute_error

In [11]:
def ReLU(Z):
    return np.maximum(Z, 0)

#Function for softmax function:
#f(x) = e ^ xi / sum(e ^ x) 
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

#Derivative of ReLU function
def ReLU_derivatite(Z):
    return Z > 0

#Function for one-hot encode
def OneHot(Y):
    result_Y = np.zeros((Y.size, Y.max() + 1))
    result_Y[np.arange(Y.size), Y] = 1
    result_Y = result_Y.T
    return result_Y

#Function for forward propagation
def forward_propagation(w_b_dictionary, X):
    number_of_z = int(len(w_b_dictionary)/2)
    z = 0
    a = X
    a_z_dictionary = {}
    for i in range(1, number_of_z):
        z = w_b_dictionary["w" + str(i)].dot(a) + w_b_dictionary["b" + str(i)]
        a = ReLU(z)
        a_z_dictionary["z" + str(i)] = z
        a_z_dictionary["a" + str(i)] = a
    z = w_b_dictionary["w" + str(number_of_z)].dot(a) + w_b_dictionary["b" + str(number_of_z)]
    a = softmax(z)
    a_z_dictionary["z" + str(number_of_z)] = z
    a_z_dictionary["a" + str(number_of_z)] = a
    return a_z_dictionary

def get_predictions(A):
    return np.argmax(A, 0)

In [12]:

def make_predictions(X, W_B_Dictionary, length_layers):
    print(X.shape)
    A_Z_dictionary = forward_propagation(W_B_Dictionary, X)
    print("a, z " + str(len(A_Z_dictionary)))
    print(A_Z_dictionary["a3"].shape)
    print(A_Z_dictionary["a2"].shape)
    print(A_Z_dictionary["a1"].shape)
    new_predictions = get_predictions(A_Z_dictionary["a" + str(length_layers - 1)])
    
    return new_predictions

def test_prediction(X_test, Y_test, index, W_B_Dictionary, predictions, layers, correct_count):
    length_layers = len(layers)

    current_image = X_test[:,index]
    current_image = current_image.reshape(784,1)
    prediction = make_predictions(current_image, W_B_Dictionary,length_layers)
    label = Y_test[index]
    
    predictions.append(prediction)

    if (int(prediction[0]) == label):
        correct_count = correct_count + 1

    # print("Prediction: ", prediction)
    # print("Label: ", label)
    return correct_count

In [13]:
data = pd.read_csv("data_testing.csv", header=None)

#Transfer data into numpy array
data = np.array(data)

n, m = data.shape

Y_test = data[0]

X_test = data[1:n]

X_test = X_test / 255
m_test, n_test = X_test.shape

In [14]:
predictions = []

correct_count = 0
number_of_correct = m


In [15]:
layers = [784, 16, 8, 2]
length_layers = len(layers)

In [16]:
w_b_dictionary = {}
for i in range(1, length_layers):
    w_b_dictionary["w" + str(i)] = np.array(pd.read_csv("w" + str(i) +".csv", header=None))
    w_b_dictionary["b" + str(i)] = np.array(pd.read_csv("b" + str(i) +".csv", header=None))
    print(w_b_dictionary["w" + str(i)].shape)
    print(w_b_dictionary["b" + str(i)].shape)

(16, 784)
(16, 1)
(8, 16)
(8, 1)
(2, 8)
(2, 1)


In [17]:
len(w_b_dictionary)

6

In [18]:
for i in range(m):
    correct_count = test_prediction(X_test, Y_test, i, w_b_dictionary, predictions, layers, correct_count)

(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, z 6
(2, 1)
(8, 1)
(16, 1)
(784, 1)
a, 

In [19]:
predictions

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),

In [20]:
accuracy = accuracy_score(Y_test, predictions)

In [21]:
accuracy

0.9314995777536494

In [22]:
precision = precision_score(Y_test, predictions, average="macro")

In [23]:
precision

0.8570293377379268

In [24]:
recall = recall_score(Y_test, predictions, average="macro")

In [25]:
recall

0.7189317385066301

In [26]:
f_score = f1_score(Y_test, predictions, average="macro")

In [27]:
f_score

0.7668660224769746

In [28]:
mse = mean_squared_error(Y_test, predictions)

In [29]:
mse

0.06850042224635058

In [30]:
mae = mean_absolute_error(Y_test, predictions)

In [31]:
mae

0.06850042224635058

In [32]:
r2 = r2_score(Y_test, predictions)

In [33]:
r2

0.24334329052883064